sudo: false

language: go

go:
  - master

os:
  - linux

branches:
  only:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - chmod +x build-docs.sh
  - ./build-docs.sh

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: docs/public
  github_token: $GITHUB_TOKEN
  email: $EMAIL
  on:
    branch: master
